// Astrophysics Quiz Questions
// Real-world calculus problems in space physics

export const astrophysicsQuizData = {
    'orbital-mechanics': [
        {
            id: 'om-1',
            type: 'multiple-choice',
            question: 'The International Space Station orbits at 400 km above Earth. If we increase the orbital radius, what happens to the orbital velocity?',
            options: [
                'Velocity increases',
                'Velocity decreases',
                'Velocity stays the same',
                'Velocity becomes zero',
            ],
            correctAnswer: 1,
            explanation: 'From v = √(GM/r), as radius (r) increases, velocity decreases. Farther orbits are slower!',
            hint: 'Think about the formula v = √(GM/r). What happens when r gets bigger?',
        },
        {
            id: 'om-2',
            type: 'multiple-choice',
            question: 'Which mathematical concept helps us find the instantaneous velocity of a planet in orbit?',
            options: [
                'Integration',
                'Derivative',
                'Multiplication',
                'Division',
            ],
            correctAnswer: 1,
            explanation: 'Derivatives give us instantaneous rate of change. Taking the derivative of position gives velocity!',
            hint: 'We need the rate of change of position with respect to time.',
        },
        {
            id: 'om-3',
            type: 'multiple-choice',
            question: 'If Earth\'s mass doubled but its radius stayed the same, what would happen to orbital velocity at the same altitude?',
            options: [
                'Increase by √2',
                'Decrease by √2',
                'Double',
                'Stay the same',
            ],
            correctAnswer: 0,
            explanation: 'From v = √(GM/r), if M doubles, v increases by √2 ≈ 1.41 times.',
            hint: 'Look at v = √(GM/r). If M doubles, what happens to √(GM)?',
        },
        {
            id: 'om-4',
            type: 'multiple-choice',
            question: 'The orbital period (time to complete one orbit) is related to orbital radius. As radius increases, the period:',
            options: [
                'Decreases',
                'Increases',
                'Stays constant',
                'Becomes zero',
            ],
            correctAnswer: 1,
            explanation: 'Kepler\'s Third Law: T² ∝ r³. Larger orbits take longer to complete!',
            hint: 'Think about the Moon vs. the ISS. Which takes longer to orbit Earth?',
        },
        {
            id: 'om-5',
            type: 'multiple-choice',
            question: 'At what point in an elliptical orbit is a planet moving fastest?',
            options: [
                'At the farthest point (aphelion)',
                'At the closest point (perihelion)',
                'At the midpoint',
                'Speed is constant',
            ],
            correctAnswer: 1,
            explanation: 'Conservation of energy! Closer to the star = more gravitational potential energy converted to kinetic energy = faster speed.',
            hint: 'Think about energy conservation. Where does the planet have more kinetic energy?',
        },
    ],
    'escape-velocity': [
        {
            id: 'ev-1',
            type: 'multiple-choice',
            question: 'Earth\'s escape velocity is about 11.2 km/s. What is the escape velocity from the Moon (which has less mass and smaller radius)?',
            options: [
                'Higher than Earth',
                'Lower than Earth',
                'Same as Earth',
                'Zero',
            ],
            correctAnswer: 1,
            explanation: 'The Moon has much less mass and smaller radius, so escape velocity is only 2.4 km/s - much lower than Earth!',
            hint: 'The Moon has weaker gravity. Does it need more or less speed to escape?',
        },
        {
            id: 'ev-2',
            type: 'multiple-choice',
            question: 'Which calculus operation do we use to derive the escape velocity formula?',
            options: [
                'Derivative',
                'Integration',
                'Limit',
                'Summation',
            ],
            correctAnswer: 1,
            explanation: 'We integrate the gravitational force over distance to find the total work needed to escape!',
            hint: 'We need to add up all the work done against gravity over a distance.',
        },
        {
            id: 'ev-3',
            type: 'multiple-choice',
            question: 'If you launch a rocket at exactly escape velocity, what happens?',
            options: [
                'It falls back to Earth',
                'It orbits Earth',
                'It escapes but slows to zero at infinity',
                'It accelerates forever',
            ],
            correctAnswer: 2,
            explanation: 'At exactly escape velocity, the rocket has just enough energy to reach infinite distance with zero velocity.',
            hint: 'Escape velocity is the minimum speed needed. What happens at the minimum?',
        },
        {
            id: 'ev-4',
            type: 'multiple-choice',
            question: 'Why is escape velocity from the Sun\'s surface much higher than from Earth?',
            options: [
                'The Sun is hotter',
                'The Sun has much more mass',
                'The Sun is farther away',
                'The Sun rotates faster',
            ],
            correctAnswer: 1,
            explanation: 'Escape velocity depends on mass and radius: v = √(2GM/r). The Sun\'s enormous mass makes its escape velocity about 618 km/s!',
            hint: 'Think about the formula v = √(2GM/r). What makes the Sun different?',
        },
        {
            id: 'ev-5',
            type: 'multiple-choice',
            question: 'A black hole has such strong gravity that even light cannot escape. What does this tell us about its escape velocity?',
            options: [
                'Less than speed of light',
                'Equal to speed of light',
                'Greater than speed of light',
                'Zero',
            ],
            correctAnswer: 2,
            explanation: 'At the event horizon, escape velocity exceeds the speed of light (299,792 km/s), so nothing can escape!',
            hint: 'If light (the fastest thing) can\'t escape, what does that mean about escape velocity?',
        },
    ],
    'gravitational-acceleration': [
        {
            id: 'ga-1',
            type: 'multiple-choice',
            question: 'On Earth\'s surface, g = 9.8 m/s². At an altitude equal to Earth\'s radius (2× distance from center), what is g?',
            options: [
                '9.8 m/s²',
                '4.9 m/s²',
                '2.45 m/s²',
                '19.6 m/s²',
            ],
            correctAnswer: 2,
            explanation: 'g ∝ 1/r². Doubling the distance reduces g by a factor of 4: 9.8/4 = 2.45 m/s²',
            hint: 'Gravity follows an inverse square law: g ∝ 1/r²',
        },
        {
            id: 'ga-2',
            type: 'multiple-choice',
            question: 'What calculus operation gives us gravitational acceleration from gravitational potential energy?',
            options: [
                'Integration',
                'Derivative',
                'Multiplication',
                'Square root',
            ],
            correctAnswer: 1,
            explanation: 'Taking the derivative of potential energy U = -GMm/r gives us force F = -GMm/r², and dividing by mass gives a = GM/r²',
            hint: 'We need the rate of change of potential energy.',
        },
        {
            id: 'ga-3',
            type: 'multiple-choice',
            question: 'Jupiter has 318 times Earth\'s mass but 11 times Earth\'s radius. How does surface gravity compare?',
            options: [
                'Much stronger than Earth',
                'About 2.5× Earth\'s gravity',
                'Same as Earth',
                'Weaker than Earth',
            ],
            correctAnswer: 1,
            explanation: 'g = GM/r². Jupiter: g ∝ 318/11² = 318/121 ≈ 2.6 times Earth\'s gravity (actually 24.8 m/s²)',
            hint: 'Use g = GM/r². More mass increases g, but larger radius decreases it.',
        },
        {
            id: 'ga-4',
            type: 'multiple-choice',
            question: 'Why do astronauts in the ISS feel weightless even though Earth\'s gravity is still 90% as strong?',
            options: [
                'They are too far from Earth',
                'They are in free fall',
                'There is no gravity in space',
                'The ISS shields them from gravity',
            ],
            correctAnswer: 1,
            explanation: 'They\'re in continuous free fall around Earth! Both they and the ISS are accelerating toward Earth at the same rate.',
            hint: 'Think about what happens when you\'re falling - you feel weightless!',
        },
        {
            id: 'ga-5',
            type: 'multiple-choice',
            question: 'At the center of Earth (r = 0), what is the gravitational acceleration?',
            options: [
                'Infinite',
                'Maximum (9.8 m/s²)',
                'Zero',
                'Negative',
            ],
            correctAnswer: 2,
            explanation: 'At the center, you\'re pulled equally in all directions, so the net gravitational force is zero!',
            hint: 'If you\'re at the center, which direction would gravity pull you?',
        },
    ],
    'light-spectra': [
        {
            id: 'ls-1',
            type: 'multiple-choice',
            question: 'To find the total energy from a star across all wavelengths, we use:',
            options: [
                'Derivative',
                'Integration',
                'Multiplication',
                'Division',
            ],
            correctAnswer: 1,
            explanation: 'Integration sums up intensity across all wavelengths: Total Energy = ∫ I(λ) dλ',
            hint: 'We need to add up contributions from all wavelengths.',
        },
        {
            id: 'ls-2',
            type: 'multiple-choice',
            question: 'A star emits most of its light in the blue wavelength. What does this tell us?',
            options: [
                'The star is cool',
                'The star is hot',
                'The star is old',
                'The star is small',
            ],
            correctAnswer: 1,
            explanation: 'Wien\'s Law: hotter objects emit more blue/UV light. Blue stars are typically 10,000-30,000 K!',
            hint: 'Think about a flame - the blue part is hotter than the red part.',
        },
        {
            id: 'ls-3',
            type: 'multiple-choice',
            question: 'When we integrate a star\'s spectrum, we\'re finding:',
            options: [
                'The star\'s temperature',
                'The star\'s distance',
                'The total luminosity',
                'The star\'s age',
            ],
            correctAnswer: 2,
            explanation: 'Integration gives us the total area under the intensity curve, which equals total luminosity (total light output).',
            hint: 'Integration finds the area under a curve. What does that represent for light intensity?',
        },
        {
            id: 'ls-4',
            type: 'multiple-choice',
            question: 'Dark lines in a star\'s spectrum are caused by:',
            options: [
                'The star being too far away',
                'Elements absorbing specific wavelengths',
                'The star being too cold',
                'Errors in measurement',
            ],
            correctAnswer: 1,
            explanation: 'Elements in the star\'s atmosphere absorb specific wavelengths, creating dark absorption lines. This tells us the star\'s composition!',
            hint: 'Different elements absorb different colors of light.',
        },
        {
            id: 'ls-5',
            type: 'multiple-choice',
            question: 'If we observe a star\'s spectrum shifted toward red wavelengths, this indicates:',
            options: [
                'The star is moving toward us',
                'The star is moving away from us',
                'The star is getting hotter',
                'The star is getting cooler',
            ],
            correctAnswer: 1,
            explanation: 'Redshift indicates the star is moving away (Doppler effect). This is how we discovered the universe is expanding!',
            hint: 'Think about the Doppler effect - like a siren moving away sounds lower pitched.',
        },
    ],
};

// Get random questions for a specific astrophysics module
export const getAstrophysicsQuestions = (moduleId, count = 5) => {
    const questions = astrophysicsQuizData[moduleId] || astrophysicsQuizData['orbital-mechanics'];

    // Shuffle and return requested number of questions
    const shuffled = [...questions].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, Math.min(count, shuffled.length));
};
